[2024-11-08T15:35:27.717+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T15:35:27.730+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: strata-lab-1-v03.fetch_and_calculate_indicators scheduled__2024-11-08T15:33:00+00:00 [queued]>
[2024-11-08T15:35:27.735+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: strata-lab-1-v03.fetch_and_calculate_indicators scheduled__2024-11-08T15:33:00+00:00 [queued]>
[2024-11-08T15:35:27.736+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-08T15:35:27.741+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): fetch_and_calculate_indicators> on 2024-11-08 15:33:00+00:00
[2024-11-08T15:35:27.751+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=492) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-08T15:35:27.752+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'strata-lab-1-v03', 'fetch_and_calculate_indicators', 'scheduled__2024-11-08T15:33:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/test-4.py', '--cfg-path', '/tmp/tmp_tozxtev']
[2024-11-08T15:35:27.753+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask fetch_and_calculate_indicators
[2024-11-08T15:35:27.753+0000] {standard_task_runner.py:72} INFO - Started process 542 to run task
[2024-11-08T15:35:27.787+0000] {task_command.py:467} INFO - Running <TaskInstance: strata-lab-1-v03.fetch_and_calculate_indicators scheduled__2024-11-08T15:33:00+00:00 [running]> on host 836a99166ce4
[2024-11-08T15:35:27.850+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='strata-lab-1-v03' AIRFLOW_CTX_TASK_ID='fetch_and_calculate_indicators' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T15:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-08T15:33:00+00:00'
[2024-11-08T15:35:27.853+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-08T15:35:27.854+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-08T15:35:27.854+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_calculate_indicators state:running start_date:2024-11-08 15:35:27.731260+00:00
[2024-11-08T15:35:27.854+0000] {logging_mixin.py:190} INFO - Dag name:strata-lab-1-v03 and current dag run status:running
[2024-11-08T15:35:27.854+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T15:35:28.415+0000] {logging_mixin.py:190} INFO - Datos de criptomonedas obtenidos:                          open      high  ...  taker_buy_quote_asset_volume  ignore
timestamp                                ...                                      
2024-11-08 07:16:00  75760.00  75803.99  ...                  6.347786e+05     0.0
2024-11-08 07:17:00  75803.99  75820.00  ...                  3.976505e+05     0.0
2024-11-08 07:18:00  75780.90  75786.00  ...                  2.556012e+05     0.0
2024-11-08 07:19:00  75762.01  75763.99  ...                  1.467347e+05     0.0
2024-11-08 07:20:00  75734.00  75734.00  ...                  2.402435e+05     0.0
...                       ...       ...  ...                           ...     ...
2024-11-08 15:31:00  76498.29  76584.60  ...                  1.312833e+07     0.0
2024-11-08 15:32:00  76551.46  76568.63  ...                  1.823855e+06     0.0
2024-11-08 15:33:00  76495.99  76538.71  ...                  2.266873e+06     0.0
2024-11-08 15:34:00  76508.00  76515.74  ...                  1.749468e+06     0.0
2024-11-08 15:35:00  76473.97  76494.00  ...                  4.300676e+05     0.0

[500 rows x 11 columns]
[2024-11-08T15:35:28.435+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'timestamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test-4.py", line 50, in fetch_and_calculate_indicators
    return asyncio.run(fetch_data_and_calculate())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test-4.py", line 39, in fetch_data_and_calculate
    'timestamp': data['timestamp'],
                 ~~~~^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'timestamp'
[2024-11-08T15:35:28.475+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-08T15:35:28.476+0000] {logging_mixin.py:190} INFO - Task start:2024-11-08 15:35:27.731260+00:00 end:2024-11-08 15:35:28.473432+00:00 duration:0.742172
[2024-11-08T15:35:28.477+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): fetch_and_calculate_indicators> dag:<DAG: strata-lab-1-v03> dagrun:<DagRun strata-lab-1-v03 @ 2024-11-08 15:33:00+00:00: scheduled__2024-11-08T15:33:00+00:00, state:running, queued_at: 2024-11-08 15:35:19.296658+00:00. externally triggered: False>
[2024-11-08T15:35:28.477+0000] {logging_mixin.py:190} INFO - Failure caused by 'timestamp'
[2024-11-08T15:35:28.478+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=strata-lab-1-v03, task_id=fetch_and_calculate_indicators, run_id=scheduled__2024-11-08T15:33:00+00:00, execution_date=20241108T153300, start_date=20241108T153527, end_date=20241108T153528
[2024-11-08T15:35:28.496+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T15:35:28.501+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task fetch_and_calculate_indicators ('timestamp'; 542)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'timestamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test-4.py", line 50, in fetch_and_calculate_indicators
    return asyncio.run(fetch_data_and_calculate())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test-4.py", line 39, in fetch_data_and_calculate
    'timestamp': data['timestamp'],
                 ~~~~^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'timestamp'
[2024-11-08T15:35:28.525+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-08T15:35:28.552+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T15:35:28.556+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
